countryDict = {
	#United Kingdom
	'ALD' : 'Alderney',
	'GSY' : 'Guernsey',
	'JSY' : 'Jersey',
	'SRK' : 'Sark',
	'AVN' : 'Avon',
	'BDF' : 'Bedfordshire',
	'BRK' : 'Berkshire',
	'BKM' : 'Buckinghamshire',
	'CAM' : 'Cambridgeshire',
	'CHS' : 'Cheshire',
	'CLV' : 'Cleveland',
	'DUR' : 'Durham',
	'CON' : 'Cornwall',
	'CUL' : 'Cumberland',
	'CMA' : 'Cumbria',
	'DBY' : 'Derbyshire',
	'DEV' : 'Devon',
	'DOR' : 'Dorset',
	'ERY' : 'East Riding of Yorkshire',
	'SXE' : 'East Sussex',
	'ESS' : 'Essex',
	'GLS' : 'Gloucestershire',
	'GTM' : 'Greater Manchester',
	'HAM' : 'Hampshire',
	'HWR' : 'Hereford and Worcester',
	'HEF' : 'Herefordshire',
	'HRT' : 'Hertfordshire',
	'HUM' : 'Humberside',
	'HUN' : 'Huntingdonshire',
	'IOW' : 'Isle of Wight',
	'KEN' : 'Kent',
	'LAN' : 'Lancashire',
	'LEI' : 'Leicestershire',
	'LIN' : 'Lincolnshire',
	'MSY' : 'Merseyside',
	'NFK' : 'Norfolk',
	'NRY' : 'North Riding of Yorkshire',
	'NYK' : 'North Yorkshire',
	'NTH' : 'Northamptonshire',
	'NBL' : 'Northumberland',
	'NTT' : 'Nottinghamshire',
	'OXF' : 'Oxfordshire',
	'RUT' : 'Rutland',
	'SAL' : 'Shropshire',
	'SOM' : 'Somerset',
	'SYK' : 'South Yorkshire',
	'STS' : 'Staffordshire',
	'SFK' : 'Suffolk',
	'SRY' : 'Surrey',
	'SSX' : 'Sussex',
	'TWR' : 'Tyne and Wear',
	'WAR' : 'Warwickshire',
	'WMD' : 'West Midlands',
	'WRY' : 'West Riding of Yorkshire',
	'SXW' : 'West Sussex',
	'WYK' : 'West Yorkshire',
	'WES' : 'Westmorland',
	'WIL' : 'Wiltshire',
	'WOR' : 'Worcestershire',
	'YKS' : 'Yorkshire',
	'ABD' : 'Aberdeenshire',
	'ANS' : 'Angus',
	'ARL' : 'Argyllshire',
	'AYR' : 'Ayrshire',
	'BAN' : 'Banffshire',
	'BEW' : 'Berwickshire',
	'BOR' : 'Borders',
	'BUT' : 'Bute',
	'CAI' : 'Caithness',
	'CEN' : 'Central',
	'CLK' : 'Clackmannanshire',
	'DGY' : 'Dumfries and Galloway',
	'DFS' : 'Dumfries-shire',
	'DNB' : 'Dunbartonshire',
	'ELN' : 'East Lothian',
	'FIF' : 'Fife',
	'GMP' : 'Grampian',
	'HLD' : 'Highland',
	'INV' : 'Inverness-shire',
	'KCD' : 'Kincardineshire',
	'KRS' : 'Kinross-shire',
	'KKD' : 'Kirkcudbrightshire',
	'LKS' : 'Lanarkshire',
	'LTN' : 'Lothian',
	'MLN' : 'Midlothian',
	'MOR' : 'Morayshire',
	'NAI' : 'Nairn',
	'OKI' : 'Orkney',
	'PEE' : 'Peebles-shire',
	'PER' : 'Perth',
	'RFW' : 'Renfrewshire',
	'ROC' : 'Ross and Cromarty',
	'ROX' : 'Roxburghshire',
	'SEL' : 'Selkirkshire',
	'SHI' : 'Shetland',
	'STI' : 'Stirlingshire',
	'STD' : 'Strathclyde',
	'SUT' : 'Sutherland',
	'TAY' : 'Tayside',
	'WLN' : 'West Lothian',
	'WIS' : 'Western Isles',
	'WIG' : 'Wigtownshire',
	'AGY' : 'Anglesey',
	'BRE' : 'Breconshire',
	'CAE' : 'Caernarvonshire',
	'CGN' : 'Cardiganshire',
	'CMN' : 'Carmarthenshire',
	'CWD' : 'Clwyd',
	'DEN' : 'Denbighshire',
	'DFD' : 'Dyfed',
	'FLN' : 'Flintshire',
	'GLA' : 'Glamorgan',
	'GNT' : 'Gwent',
	'GWN' : 'Gwynedd',
	'MER' : 'Merionethshire',
	'MGM' : 'Mid Glamorgan',
	'MON' : 'Monmouthshire',
	'MGY' : 'Montgomeryshire',
	'PEM' : 'Pembrokeshire',
	'POW' : 'Powys',
	'RAD' : 'Radnorshire',
	'SGM' : 'South Glamorgan',
	'WGM' : 'West Glamorgan',
	#Australia
	'NSW' : 'New South Wales',
	'QLD' : 'Queensland',
	'SA'  : 'South Australia',
	'TAS' : 'Tasmania',
	'VIC' : 'Victoria',
	'WA'  : 'Western Australia',
	'ACT' : 'Australian Capital Territory',
	'JBT' : 'Jervis Bay Territory',
	'NT'  : 'Northern Territory'
}
